// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package client

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

type ActivateOffchainWorkflowRequest struct {
	WorkflowID string `json:"workflowId"`
}

type ActivateOffchainWorkflowResponse struct {
	Workflow *OffchainWorkflow `json:"workflow"`
}

type ActorInfoInput struct {
	UserID         *string `json:"userId,omitempty"`
	OrganizationID *string `json:"organizationId,omitempty"`
	MachineID      *string `json:"machineId,omitempty"`
}

type AggregatedSpendValue struct {
	ResourceType string `json:"resourceType"`
	SpendValue   string `json:"spendValue"`
}

type AggregatedWorkflowResourceConsumption struct {
	DimensionValue        string                  `json:"dimensionValue"`
	AggregatedSpendValues []*AggregatedSpendValue `json:"aggregatedSpendValues"`
}

type AuthCodeTokenExchangeRequest struct {
	Code         string `json:"code"`
	CodeVerifier string `json:"codeVerifier"`
	RedirectURI  string `json:"redirectUri"`
}

type AuthCodeTokenExchangeResponse struct {
	AccessToken string `json:"accessToken"`
	ExpiresIn   int    `json:"expiresIn"`
}

type CapabilityExecutionError struct {
	Error string `json:"error"`
	Count int    `json:"count"`
}

type CommandInfoInput struct {
	Action     *string     `json:"action,omitempty"`
	Subcommand *string     `json:"subcommand,omitempty"`
	Args       []string    `json:"args,omitempty"`
	Flags      []*KeyValue `json:"flags,omitempty"`
}

type CreateAPIKeyRequest struct {
	ExpiryDate  time.Time `json:"expiryDate"`
	DisplayName *string   `json:"displayName,omitempty"`
}

type CreateAPIKeyResponse struct {
	APIKeyID    string `json:"apiKeyId"`
	APIKeyToken string `json:"apiKeyToken"`
}

type DeleteOffchainWorkflowRequest struct {
	WorkflowID string `json:"workflowId"`
}

type DeleteOffchainWorkflowResponse struct {
	WorkflowID string `json:"workflowId"`
}

type ExecutionError struct {
	Error string `json:"error"`
	Count int    `json:"count"`
}

type Forwarder struct {
	ChainSelector string `json:"chainSelector"`
	Address       string `json:"address"`
}

type GeneratePresignedGetURLRequest struct {
	WorkflowID              string       `json:"workflowId"`
	ArtifactType            ArtifactType `json:"artifactType"`
	WorkflowRegistryAddress string       `json:"workflowRegistryAddress"`
	ChainSelector           string       `json:"chainSelector"`
}

type GeneratePresignedGetURLResponse struct {
	PresignedGetURL string `json:"presignedGetUrl"`
}

type GeneratePresignedPostURLRequest struct {
	WorkflowID              string       `json:"workflowId"`
	ArtifactType            ArtifactType `json:"artifactType"`
	ContentHash             string       `json:"contentHash"`
	WorkflowOwnerAddress    string       `json:"workflowOwnerAddress"`
	WorkflowRegistryAddress *string      `json:"workflowRegistryAddress,omitempty"`
	ChainSelector           *string      `json:"chainSelector,omitempty"`
}

type GeneratePresignedPostURLResponse struct {
	PresignedPostURL    string    `json:"presignedPostUrl"`
	PresignedPostFields []*Header `json:"presignedPostFields"`
}

type GenerateUnsignedGetURLRequest struct {
	WorkflowID              string       `json:"workflowId"`
	ArtifactType            ArtifactType `json:"artifactType"`
	WorkflowRegistryAddress *string      `json:"workflowRegistryAddress,omitempty"`
	ChainSelector           *string      `json:"chainSelector,omitempty"`
}

type GenerateUnsignedGetURLResponse struct {
	UnsignedGetURL string `json:"unsignedGetUrl"`
}

type GetAggregatedWorkflowResourceConsumptionFilters struct {
	Dimension                      ResourceConsumptionGroupDimension `json:"dimension"`
	WorkflowUuids                  []string                          `json:"workflowUuids,omitempty"`
	WorkflowExecutionIds           []string                          `json:"workflowExecutionIds,omitempty"`
	WorkflowRegistryChainSelectors []string                          `json:"workflowRegistryChainSelectors,omitempty"`
	ResourceTypes                  []string                          `json:"resourceTypes,omitempty"`
	FromTimestamp                  *time.Time                        `json:"fromTimestamp,omitempty"`
	ToTimestamp                    *time.Time                        `json:"toTimestamp,omitempty"`
	SplitGasResourcePerChain       bool                              `json:"splitGasResourcePerChain"`
}

type GetOffchainWorkflowByIDRequest struct {
	WorkflowID string `json:"workflowId"`
}

type GetOffchainWorkflowByIDResponse struct {
	Workflow *OffchainWorkflow `json:"workflow"`
}

type GetOffchainWorkflowByNameRequest struct {
	WorkflowName string `json:"workflowName"`
}

type GetOffchainWorkflowByNameResponse struct {
	Workflow *OffchainWorkflow `json:"workflow"`
}

type GetOffchainWorkflowByOwnerAndNameRequest struct {
	Owner        string `json:"owner"`
	WorkflowName string `json:"workflowName"`
}

type GetOffchainWorkflowByOwnerAndNameResponse struct {
	Workflow *OffchainWorkflow `json:"workflow"`
}

type GetWorkflowResourceConsumptionFilters struct {
	WorkflowIds                    []string   `json:"workflowIds,omitempty"`
	WorkflowOwners                 []string   `json:"workflowOwners,omitempty"`
	WorkflowExecutionIds           []string   `json:"workflowExecutionIds,omitempty"`
	WorkflowRegistryChainSelectors []string   `json:"workflowRegistryChainSelectors,omitempty"`
	ResourceTypes                  []string   `json:"resourceTypes,omitempty"`
	FromTimestamp                  *time.Time `json:"fromTimestamp,omitempty"`
	ToTimestamp                    *time.Time `json:"toTimestamp,omitempty"`
	SplitGasResourcePerChain       bool       `json:"splitGasResourcePerChain"`
}

type Header struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type InitiateLinkingRequest struct {
	WorkflowOwnerAddress string              `json:"workflowOwnerAddress"`
	WorkflowOwnerLabel   *string             `json:"workflowOwnerLabel,omitempty"`
	Environment          Environment         `json:"environment"`
	RequestProcess       *LinkRequestProcess `json:"requestProcess,omitempty"`
}

type InitiateLinkingResponse struct {
	OwnershipProofHash   string    `json:"ownershipProofHash"`
	WorkflowOwnerAddress string    `json:"workflowOwnerAddress"`
	ValidUntil           time.Time `json:"validUntil"`
	Signature            string    `json:"signature"`
	ChainSelector        string    `json:"chainSelector"`
	ContractAddress      string    `json:"contractAddress"`
	TransactionData      string    `json:"transactionData"`
	FunctionSignature    string    `json:"functionSignature"`
	FunctionArgs         []string  `json:"functionArgs"`
}

type InitiateUnlinkingRequest struct {
	WorkflowOwnerAddress string      `json:"workflowOwnerAddress"`
	Environment          Environment `json:"environment"`
}

type InitiateUnlinkingResponse struct {
	OwnershipProofHash   string    `json:"ownershipProofHash"`
	WorkflowOwnerAddress string    `json:"workflowOwnerAddress"`
	ValidUntil           time.Time `json:"validUntil"`
	Signature            string    `json:"signature"`
	ChainSelector        string    `json:"chainSelector"`
	ContractAddress      string    `json:"contractAddress"`
	TransactionData      string    `json:"transactionData"`
	FunctionSignature    string    `json:"functionSignature"`
	FunctionArgs         []string  `json:"functionArgs"`
}

type InviteOrganizationMembersResponse struct {
	Success bool `json:"success"`
}

type KeyValue struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type ListOffchainWorkflowsRequest struct {
	Limit                 int        `json:"limit"`
	LastWorkflowCreatedAt *time.Time `json:"lastWorkflowCreatedAt,omitempty"`
	LastWorkflowID        *string    `json:"lastWorkflowId,omitempty"`
}

type ListOffchainWorkflowsResponse struct {
	Workflows []*OffchainWorkflow `json:"workflows"`
}

type ListWorkflowOwnersResponse struct {
	LinkedOwners   []*WorkflowOwner `json:"linkedOwners,omitempty"`
	UnlinkedOwners []*WorkflowOwner `json:"unlinkedOwners,omitempty"`
}

type MachineInfoInput struct {
	OsName       *string `json:"osName,omitempty"`
	OsVersion    *string `json:"osVersion,omitempty"`
	Architecture *string `json:"architecture,omitempty"`
}

type Mutation struct {
}

type OffchainWorkflow struct {
	WorkflowID     string                 `json:"workflowId"`
	Owner          string                 `json:"owner"`
	CreatedAt      time.Time              `json:"createdAt"`
	UpdatedAt      time.Time              `json:"updatedAt"`
	Status         OffchainWorkflowStatus `json:"status"`
	WorkflowName   string                 `json:"workflowName"`
	BinaryURL      string                 `json:"binaryUrl"`
	ConfigURL      string                 `json:"configUrl"`
	Tag            string                 `json:"tag"`
	Attributes     string                 `json:"attributes"`
	DonFamily      string                 `json:"donFamily"`
	OrganizationID string                 `json:"organizationId"`
}

type OffchainWorkflowInput struct {
	WorkflowID   string                 `json:"workflowId"`
	Status       OffchainWorkflowStatus `json:"status"`
	WorkflowName string                 `json:"workflowName"`
	BinaryURL    string                 `json:"binaryUrl"`
	ConfigURL    *string                `json:"configUrl,omitempty"`
	Tag          *string                `json:"tag,omitempty"`
	Attributes   *string                `json:"attributes,omitempty"`
	DonFamily    string                 `json:"donFamily"`
}

// On-chain contract reference (address + chain selector).
type OnChainContract struct {
	ChainSelector string `json:"chainSelector"`
	Address       string `json:"address"`
}

type Organization struct {
	OrganizationID    string                        `json:"organizationId"`
	DisplayName       string                        `json:"displayName"`
	CreatedAt         time.Time                     `json:"createdAt"`
	UpdatedAt         time.Time                     `json:"updatedAt"`
	RestrictionStatus OrganizationRestrictionStatus `json:"restrictionStatus"`
	ActiveStatus      EntityActiveStatus            `json:"activeStatus"`
	TenantID          int                           `json:"tenantId"`
}

type OrganizationAccount struct {
	MemberID       string       `json:"memberId"`
	UserID         *string      `json:"userId,omitempty"`
	OrganizationID string       `json:"organizationId"`
	EmailAddress   string       `json:"emailAddress"`
	DisplayName    string       `json:"displayName"`
	MemberType     *MemberType  `json:"memberType,omitempty"`
	MemberStatus   MemberStatus `json:"memberStatus"`
	CreatedAt      time.Time    `json:"createdAt"`
	UpdatedAt      time.Time    `json:"updatedAt"`
	InvitedByUser  *string      `json:"invitedByUser,omitempty"`
	InvitedAt      *time.Time   `json:"invitedAt,omitempty"`
	JoinedAt       *time.Time   `json:"joinedAt,omitempty"`
	RemovedByUser  *string      `json:"removedByUser,omitempty"`
	RemovedAt      *time.Time   `json:"removedAt,omitempty"`
}

type OrganizationAccountInviteParams struct {
	EmailAddress string  `json:"emailAddress"`
	DisplayName  *string `json:"displayName,omitempty"`
}

type OrganizationAPIKeyDetails struct {
	APIKeyID       string             `json:"apiKeyId"`
	OrganizationID string             `json:"organizationId"`
	UserID         *string            `json:"userId,omitempty"`
	DisplayName    *string            `json:"displayName,omitempty"`
	CreatedAt      time.Time          `json:"createdAt"`
	UpdatedAt      time.Time          `json:"updatedAt"`
	ExpiresAt      time.Time          `json:"expiresAt"`
	GeneratedAt    time.Time          `json:"generatedAt"`
	ActiveStatus   EntityActiveStatus `json:"activeStatus"`
}

type OrganizationAPIKeyFilters struct {
	APIKeyScope    *OrganizationAPIKeyScope `json:"apiKeyScope,omitempty"`
	IncludeExpired *bool                    `json:"includeExpired,omitempty"`
	ActiveStatus   []EntityActiveStatus     `json:"activeStatus,omitempty"`
}

type OrganizationMemberFilters struct {
	MemberStatus []MemberStatus `json:"memberStatus,omitempty"`
	MemberType   []MemberType   `json:"memberType,omitempty"`
}

type Page struct {
	Number *int `json:"number,omitempty"`
	Size   *int `json:"size,omitempty"`
}

type PauseOffchainWorkflowRequest struct {
	WorkflowID string `json:"workflowId"`
}

type PauseOffchainWorkflowResponse struct {
	Workflow *OffchainWorkflow `json:"workflow"`
}

type Query struct {
}

type Registry struct {
	ID               string            `json:"id"`
	Label            string            `json:"label"`
	Type             RegistryType      `json:"type"`
	ChainSelector    *string           `json:"chainSelector,omitempty"`
	Address          *string           `json:"address,omitempty"`
	SecretsAuthFlows []SecretsAuthFlow `json:"secretsAuthFlows"`
}

type RemoveOrganizationMembersResponse struct {
	Success bool `json:"success"`
}

type ReportUserEventResponse struct {
	Success bool    `json:"success"`
	Message *string `json:"message,omitempty"`
}

type RequestDeploymentAccessInput struct {
	Description string  `json:"description"`
	WorkflowURL *string `json:"workflowUrl,omitempty"`
}

type RequestDeploymentAccessResponse struct {
	Success bool    `json:"success"`
	Message *string `json:"message,omitempty"`
}

type RequestHelpInput struct {
	IssueType   SupportTicketRequestType `json:"issueType"`
	Product     SupportTicketProduct     `json:"product"`
	Description string                   `json:"description"`
}

type RequestHelpResponse struct {
	Success bool    `json:"success"`
	Message *string `json:"message,omitempty"`
}

type RevokeAPIKeyResponse struct {
	Success bool `json:"success"`
}

type RotateAPIKeyRequest struct {
	APIKeyID   string     `json:"apiKeyId"`
	ExpiryDate *time.Time `json:"expiryDate,omitempty"`
}

type RotateAPIKeyResponse struct {
	APIKeyToken string `json:"apiKeyToken"`
}

// Tenant configuration for CLI context.
type TenantConfig struct {
	TenantID string `json:"tenantId"`
	// Default DON family for this tenant. Overridable by CLI.
	DefaultDonFamily string `json:"defaultDonFamily"`
	// Vault DON gateway URL for secrets management.
	VaultGatewayURL string `json:"vaultGatewayUrl"`
	// CapabilitiesRegistry contract for this tenant.
	CapabilitiesRegistry *OnChainContract `json:"capabilitiesRegistry"`
	Registries           []*Registry      `json:"registries"`
	Forwarders           []*Forwarder     `json:"forwarders"`
}

type UpdateAccountDetailsResponse struct {
	Success bool `json:"success"`
}

type UpdateAPIKeyRequest struct {
	APIKeyID    string     `json:"apiKeyId"`
	ExpiryDate  *time.Time `json:"expiryDate,omitempty"`
	DisplayName *string    `json:"displayName,omitempty"`
}

type UpdateAPIKeyResponse struct {
	Success bool `json:"success"`
}

type UpdateOrganizationDetailsResponse struct {
	Success bool `json:"success"`
}

type UpdateOwnerMetadataRequest struct {
	WorkflowOwnerAddress  string      `json:"workflowOwnerAddress"`
	Environment           Environment `json:"environment"`
	NewWorkflowOwnerLabel string      `json:"newWorkflowOwnerLabel"`
}

type UpdateOwnerMetadataResponse struct {
	Success bool `json:"success"`
}

type UpsertOffchainWorkflowRequest struct {
	Workflow *OffchainWorkflowInput `json:"workflow"`
}

type UpsertOffchainWorkflowResponse struct {
	Workflow *OffchainWorkflow `json:"workflow"`
}

type UserEventInput struct {
	CliVersion   *string            `json:"cliVersion,omitempty"`
	ExitCode     *int               `json:"exitCode,omitempty"`
	ErrorMessage *string            `json:"errorMessage,omitempty"`
	Actor        *ActorInfoInput    `json:"actor,omitempty"`
	Workflow     *WorkflowInfoInput `json:"workflow,omitempty"`
	Machine      *MachineInfoInput  `json:"machine,omitempty"`
	Command      *CommandInfoInput  `json:"command,omitempty"`
	Attributes   []*KeyValue        `json:"attributes,omitempty"`
}

type VaultAuthorizationURLRequest struct {
	CodeChallenge        string          `json:"codeChallenge"`
	RedirectURI          string          `json:"redirectUri"`
	RequestDigest        string          `json:"requestDigest"`
	WorkflowOwnerAddress *string         `json:"workflowOwnerAddress,omitempty"`
	Permission           VaultPermission `json:"permission"`
}

type VaultAuthorizationURLResponse struct {
	URL string `json:"url"`
}

type VerifyAPIKeyResponse struct {
	VerificationStatus APIKeyVerificationStatus   `json:"verificationStatus"`
	APIKeyDetails      *OrganizationAPIKeyDetails `json:"apiKeyDetails,omitempty"`
	Metadata           *string                    `json:"metadata,omitempty"`
}

type Workflow struct {
	UUID                   string                          `json:"uuid"`
	OwnerAddress           string                          `json:"ownerAddress"`
	Name                   string                          `json:"name"`
	WorkflowID             string                          `json:"workflowId"`
	Status                 WorkflowDeploymentStatus        `json:"status"`
	RegisteredAt           time.Time                       `json:"registeredAt"`
	CreditUsed             *string                         `json:"creditUsed,omitempty"`
	ExecutedAt             *time.Time                      `json:"executedAt,omitempty"`
	ExecutionCount         int                             `json:"executionCount"`
	ExecutionCountByStatus *WorkflowExecutionCountByStatus `json:"executionCountByStatus"`
	WorkflowSource         string                          `json:"workflowSource"`
	HasTeeExecutions       bool                            `json:"hasTeeExecutions"`
	HasNonTeeExecutions    bool                            `json:"hasNonTeeExecutions"`
}

type WorkflowActivityInput struct {
	WorkflowUUID *string    `json:"workflowUUID,omitempty"`
	From         *time.Time `json:"from,omitempty"`
	To           *time.Time `json:"to,omitempty"`
}

type WorkflowActivityOutput struct {
	Data []*WorkflowActivityRow `json:"data,omitempty"`
}

type WorkflowActivityRow struct {
	From         time.Time `json:"from"`
	To           time.Time `json:"to"`
	SuccessCount int       `json:"successCount"`
	FailureCount int       `json:"failureCount"`
}

type WorkflowDeployment struct {
	UUID                   string                          `json:"uuid"`
	WorkflowID             string                          `json:"workflowID"`
	ErrorMessage           *string                         `json:"errorMessage,omitempty"`
	TxHash                 *string                         `json:"txHash,omitempty"`
	BinaryURL              *string                         `json:"binaryURL,omitempty"`
	ConfigURL              *string                         `json:"configURL,omitempty"`
	Status                 WorkflowDeploymentStatus        `json:"status"`
	DeployedAt             time.Time                       `json:"deployedAt"`
	ExecutionCountByStatus *WorkflowExecutionCountByStatus `json:"executionCountByStatus,omitempty"`
	WorkflowSource         string                          `json:"workflowSource"`
	HasTeeExecutions       bool                            `json:"hasTeeExecutions"`
	HasNonTeeExecutions    bool                            `json:"hasNonTeeExecutions"`
}

type WorkflowDeploymentInput struct {
	UUID string `json:"uuid"`
}

type WorkflowDeploymentOrderBy struct {
	Field WorkflowDeploymentOrderByField `json:"field"`
	Order SortingOrder                   `json:"order"`
}

type WorkflowDeploymentOutput struct {
	Data *WorkflowDeployment `json:"data"`
}

type WorkflowDeploymentsInput struct {
	WorkflowUUID string                     `json:"workflowUUID"`
	Status       []WorkflowDeploymentStatus `json:"status,omitempty"`
	From         *time.Time                 `json:"from,omitempty"`
	To           *time.Time                 `json:"to,omitempty"`
	Search       *string                    `json:"search,omitempty"`
	OrderBy      *WorkflowDeploymentOrderBy `json:"orderBy,omitempty"`
	Page         *Page                      `json:"page,omitempty"`
}

type WorkflowDeploymentsOutput struct {
	Data  []*WorkflowDeployment `json:"data"`
	Count int                   `json:"count"`
}

type WorkflowExecution struct {
	UUID             string                             `json:"uuid"`
	WorkflowUUID     string                             `json:"workflowUUID"`
	ID               string                             `json:"id"`
	WorkflowName     string                             `json:"workflowName"`
	WorkflowID       string                             `json:"workflowId"`
	Status           WorkflowExecutionStatus            `json:"status"`
	StartedAt        time.Time                          `json:"startedAt"`
	FinishedAt       *time.Time                         `json:"finishedAt,omitempty"`
	CreditUsed       *string                            `json:"creditUsed,omitempty"`
	Errors           []*ExecutionError                  `json:"errors,omitempty"`
	ExecutedInTee    *bool                              `json:"executedInTee,omitempty"`
	ClassifiedStatus *WorkflowExecutionClassifiedStatus `json:"classifiedStatus,omitempty"`
}

type WorkflowExecutionCountByStatus struct {
	Success int `json:"success"`
	Failure int `json:"failure"`
}

type WorkflowExecutionEvent struct {
	CapabilityID string                      `json:"capabilityID"`
	Status       string                      `json:"status"`
	StartedAt    time.Time                   `json:"startedAt"`
	FinishedAt   *time.Time                  `json:"finishedAt,omitempty"`
	Errors       []*CapabilityExecutionError `json:"errors,omitempty"`
	Method       *string                     `json:"method,omitempty"`
}

type WorkflowExecutionEventsInput struct {
	WorkflowExecutionUUID string  `json:"workflowExecutionUUID"`
	CapabilityID          *string `json:"capabilityID,omitempty"`
	Status                *string `json:"status,omitempty"`
}

type WorkflowExecutionEventsOutput struct {
	Data []*WorkflowExecutionEvent `json:"data,omitempty"`
}

type WorkflowExecutionInput struct {
	UUID string `json:"uuid"`
}

type WorkflowExecutionLog struct {
	NodeID    string    `json:"nodeID"`
	Message   string    `json:"message"`
	Timestamp time.Time `json:"timestamp"`
}

type WorkflowExecutionLogsInput struct {
	WorkflowExecutionUUID string `json:"workflowExecutionUUID"`
}

type WorkflowExecutionLogsOutput struct {
	Data []*WorkflowExecutionLog `json:"data,omitempty"`
}

type WorkflowExecutionOrderBy struct {
	Field WorkflowExecutionOrderByField `json:"field"`
	Order SortingOrder                  `json:"order"`
}

type WorkflowExecutionOutput struct {
	Data *WorkflowExecution `json:"data,omitempty"`
}

type WorkflowExecutionsInput struct {
	WorkflowUUID *string                   `json:"workflowUuid,omitempty"`
	Status       []WorkflowExecutionStatus `json:"status,omitempty"`
	Search       *string                   `json:"search,omitempty"`
	From         *time.Time                `json:"from,omitempty"`
	To           *time.Time                `json:"to,omitempty"`
	OrderBy      *WorkflowExecutionOrderBy `json:"orderBy,omitempty"`
	Page         *Page                     `json:"page,omitempty"`
}

type WorkflowExecutionsOutput struct {
	Data  []*WorkflowExecution `json:"data"`
	Count int                  `json:"count"`
}

type WorkflowInfoInput struct {
	OwnerAddress *string `json:"ownerAddress,omitempty"`
	Name         *string `json:"name,omitempty"`
	ID           *string `json:"id,omitempty"`
	Language     *string `json:"language,omitempty"`
}

type WorkflowInput struct {
	UUID string    `json:"uuid"`
	From time.Time `json:"from"`
}

type WorkflowOrderBy struct {
	Field WorkflowOrderByField `json:"field"`
	Order SortingOrder         `json:"order"`
}

type WorkflowOutput struct {
	Data *Workflow `json:"data"`
}

type WorkflowOwner struct {
	WorkflowOwnerAddress string                      `json:"workflowOwnerAddress"`
	WorkflowOwnerLabel   *string                     `json:"workflowOwnerLabel,omitempty"`
	Environment          Environment                 `json:"environment"`
	VerificationStatus   OwnershipVerificationStatus `json:"verificationStatus"`
	VerifiedAt           *time.Time                  `json:"verifiedAt,omitempty"`
	ChainSelector        string                      `json:"chainSelector"`
	ContractAddress      string                      `json:"contractAddress"`
	RequestProcess       *LinkRequestProcess         `json:"requestProcess,omitempty"`
}

type WorkflowOwnersFilters struct {
	LinkStatus LinkStatusFilter `json:"linkStatus"`
}

type WorkflowResourceConsumption struct {
	OrganizationID                string          `json:"organizationId"`
	WorkflowID                    string          `json:"workflowId"`
	WorkflowOwner                 string          `json:"workflowOwner"`
	WorkflowExecutionID           string          `json:"workflowExecutionId"`
	WorkflowRegistryChainSelector string          `json:"workflowRegistryChainSelector"`
	ResourceType                  string          `json:"resourceType"`
	MeasurementUnit               MeasurementUnit `json:"measurementUnit"`
	SpendValue                    string          `json:"spendValue"`
	CreatedAt                     time.Time       `json:"createdAt"`
}

type WorkflowsInput struct {
	WorkflowOwnerAddress []string                   `json:"workflowOwnerAddress,omitempty"`
	Status               []WorkflowDeploymentStatus `json:"status,omitempty"`
	Search               *string                    `json:"search,omitempty"`
	OrderBy              *WorkflowOrderBy           `json:"orderBy,omitempty"`
	Page                 *Page                      `json:"page,omitempty"`
}

type WorkflowsOutput struct {
	Data  []*Workflow `json:"data"`
	Count int         `json:"count"`
}

type APIKeyVerificationStatus string

const (
	APIKeyVerificationStatusValid   APIKeyVerificationStatus = "VALID"
	APIKeyVerificationStatusInvalid APIKeyVerificationStatus = "INVALID"
	APIKeyVerificationStatusExpired APIKeyVerificationStatus = "EXPIRED"
)

var AllAPIKeyVerificationStatus = []APIKeyVerificationStatus{
	APIKeyVerificationStatusValid,
	APIKeyVerificationStatusInvalid,
	APIKeyVerificationStatusExpired,
}

func (e APIKeyVerificationStatus) IsValid() bool {
	switch e {
	case APIKeyVerificationStatusValid, APIKeyVerificationStatusInvalid, APIKeyVerificationStatusExpired:
		return true
	}
	return false
}

func (e APIKeyVerificationStatus) String() string {
	return string(e)
}

func (e *APIKeyVerificationStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = APIKeyVerificationStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ApiKeyVerificationStatus", str)
	}
	return nil
}

func (e APIKeyVerificationStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *APIKeyVerificationStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e APIKeyVerificationStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ArtifactType string

const (
	ArtifactTypeBinary ArtifactType = "BINARY"
	ArtifactTypeConfig ArtifactType = "CONFIG"
)

var AllArtifactType = []ArtifactType{
	ArtifactTypeBinary,
	ArtifactTypeConfig,
}

func (e ArtifactType) IsValid() bool {
	switch e {
	case ArtifactTypeBinary, ArtifactTypeConfig:
		return true
	}
	return false
}

func (e ArtifactType) String() string {
	return string(e)
}

func (e *ArtifactType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ArtifactType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ArtifactType", str)
	}
	return nil
}

func (e ArtifactType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ArtifactType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ArtifactType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type EntityActiveStatus string

const (
	EntityActiveStatusActive  EntityActiveStatus = "ACTIVE"
	EntityActiveStatusDeleted EntityActiveStatus = "DELETED"
)

var AllEntityActiveStatus = []EntityActiveStatus{
	EntityActiveStatusActive,
	EntityActiveStatusDeleted,
}

func (e EntityActiveStatus) IsValid() bool {
	switch e {
	case EntityActiveStatusActive, EntityActiveStatusDeleted:
		return true
	}
	return false
}

func (e EntityActiveStatus) String() string {
	return string(e)
}

func (e *EntityActiveStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = EntityActiveStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid EntityActiveStatus", str)
	}
	return nil
}

func (e EntityActiveStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *EntityActiveStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e EntityActiveStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type Environment string

const (
	EnvironmentProductionMainnet Environment = "PRODUCTION_MAINNET"
	EnvironmentProductionTestnet Environment = "PRODUCTION_TESTNET"
)

var AllEnvironment = []Environment{
	EnvironmentProductionMainnet,
	EnvironmentProductionTestnet,
}

func (e Environment) IsValid() bool {
	switch e {
	case EnvironmentProductionMainnet, EnvironmentProductionTestnet:
		return true
	}
	return false
}

func (e Environment) String() string {
	return string(e)
}

func (e *Environment) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Environment(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Environment", str)
	}
	return nil
}

func (e Environment) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Environment) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Environment) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type LinkRequestProcess string

const (
	LinkRequestProcessEoa  LinkRequestProcess = "EOA"
	LinkRequestProcessMsig LinkRequestProcess = "MSIG"
)

var AllLinkRequestProcess = []LinkRequestProcess{
	LinkRequestProcessEoa,
	LinkRequestProcessMsig,
}

func (e LinkRequestProcess) IsValid() bool {
	switch e {
	case LinkRequestProcessEoa, LinkRequestProcessMsig:
		return true
	}
	return false
}

func (e LinkRequestProcess) String() string {
	return string(e)
}

func (e *LinkRequestProcess) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = LinkRequestProcess(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid LinkRequestProcess", str)
	}
	return nil
}

func (e LinkRequestProcess) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *LinkRequestProcess) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e LinkRequestProcess) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type LinkStatusFilter string

const (
	LinkStatusFilterLinkedOnly   LinkStatusFilter = "LINKED_ONLY"
	LinkStatusFilterUnlinkedOnly LinkStatusFilter = "UNLINKED_ONLY"
)

var AllLinkStatusFilter = []LinkStatusFilter{
	LinkStatusFilterLinkedOnly,
	LinkStatusFilterUnlinkedOnly,
}

func (e LinkStatusFilter) IsValid() bool {
	switch e {
	case LinkStatusFilterLinkedOnly, LinkStatusFilterUnlinkedOnly:
		return true
	}
	return false
}

func (e LinkStatusFilter) String() string {
	return string(e)
}

func (e *LinkStatusFilter) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = LinkStatusFilter(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid LinkStatusFilter", str)
	}
	return nil
}

func (e LinkStatusFilter) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *LinkStatusFilter) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e LinkStatusFilter) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type MeasurementUnit string

const (
	MeasurementUnitMeasurementUnitUnspecified  MeasurementUnit = "MEASUREMENT_UNIT_UNSPECIFIED"
	MeasurementUnitMeasurementUnitBytes        MeasurementUnit = "MEASUREMENT_UNIT_BYTES"
	MeasurementUnitMeasurementUnitMilliseconds MeasurementUnit = "MEASUREMENT_UNIT_MILLISECONDS"
	MeasurementUnitMeasurementUnitOperations   MeasurementUnit = "MEASUREMENT_UNIT_OPERATIONS"
	MeasurementUnitMeasurementUnitCost         MeasurementUnit = "MEASUREMENT_UNIT_COST"
)

var AllMeasurementUnit = []MeasurementUnit{
	MeasurementUnitMeasurementUnitUnspecified,
	MeasurementUnitMeasurementUnitBytes,
	MeasurementUnitMeasurementUnitMilliseconds,
	MeasurementUnitMeasurementUnitOperations,
	MeasurementUnitMeasurementUnitCost,
}

func (e MeasurementUnit) IsValid() bool {
	switch e {
	case MeasurementUnitMeasurementUnitUnspecified, MeasurementUnitMeasurementUnitBytes, MeasurementUnitMeasurementUnitMilliseconds, MeasurementUnitMeasurementUnitOperations, MeasurementUnitMeasurementUnitCost:
		return true
	}
	return false
}

func (e MeasurementUnit) String() string {
	return string(e)
}

func (e *MeasurementUnit) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = MeasurementUnit(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid MeasurementUnit", str)
	}
	return nil
}

func (e MeasurementUnit) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *MeasurementUnit) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e MeasurementUnit) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type MemberStatus string

const (
	MemberStatusInvited MemberStatus = "INVITED"
	MemberStatusJoined  MemberStatus = "JOINED"
	MemberStatusRemoved MemberStatus = "REMOVED"
)

var AllMemberStatus = []MemberStatus{
	MemberStatusInvited,
	MemberStatusJoined,
	MemberStatusRemoved,
}

func (e MemberStatus) IsValid() bool {
	switch e {
	case MemberStatusInvited, MemberStatusJoined, MemberStatusRemoved:
		return true
	}
	return false
}

func (e MemberStatus) String() string {
	return string(e)
}

func (e *MemberStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = MemberStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid MemberStatus", str)
	}
	return nil
}

func (e MemberStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *MemberStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e MemberStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type MemberType string

const (
	MemberTypeRoot  MemberType = "ROOT"
	MemberTypeAdmin MemberType = "ADMIN"
)

var AllMemberType = []MemberType{
	MemberTypeRoot,
	MemberTypeAdmin,
}

func (e MemberType) IsValid() bool {
	switch e {
	case MemberTypeRoot, MemberTypeAdmin:
		return true
	}
	return false
}

func (e MemberType) String() string {
	return string(e)
}

func (e *MemberType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = MemberType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid MemberType", str)
	}
	return nil
}

func (e MemberType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *MemberType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e MemberType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type OffchainWorkflowStatus string

const (
	OffchainWorkflowStatusWorkflowStatusUnspecified OffchainWorkflowStatus = "WORKFLOW_STATUS_UNSPECIFIED"
	OffchainWorkflowStatusWorkflowStatusActive      OffchainWorkflowStatus = "WORKFLOW_STATUS_ACTIVE"
	OffchainWorkflowStatusWorkflowStatusPaused      OffchainWorkflowStatus = "WORKFLOW_STATUS_PAUSED"
)

var AllOffchainWorkflowStatus = []OffchainWorkflowStatus{
	OffchainWorkflowStatusWorkflowStatusUnspecified,
	OffchainWorkflowStatusWorkflowStatusActive,
	OffchainWorkflowStatusWorkflowStatusPaused,
}

func (e OffchainWorkflowStatus) IsValid() bool {
	switch e {
	case OffchainWorkflowStatusWorkflowStatusUnspecified, OffchainWorkflowStatusWorkflowStatusActive, OffchainWorkflowStatusWorkflowStatusPaused:
		return true
	}
	return false
}

func (e OffchainWorkflowStatus) String() string {
	return string(e)
}

func (e *OffchainWorkflowStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = OffchainWorkflowStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid OffchainWorkflowStatus", str)
	}
	return nil
}

func (e OffchainWorkflowStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *OffchainWorkflowStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e OffchainWorkflowStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type OrganizationAPIKeyScope string

const (
	OrganizationAPIKeyScopeUserKeys OrganizationAPIKeyScope = "USER_KEYS"
	OrganizationAPIKeyScopeOrgKeys  OrganizationAPIKeyScope = "ORG_KEYS"
)

var AllOrganizationAPIKeyScope = []OrganizationAPIKeyScope{
	OrganizationAPIKeyScopeUserKeys,
	OrganizationAPIKeyScopeOrgKeys,
}

func (e OrganizationAPIKeyScope) IsValid() bool {
	switch e {
	case OrganizationAPIKeyScopeUserKeys, OrganizationAPIKeyScopeOrgKeys:
		return true
	}
	return false
}

func (e OrganizationAPIKeyScope) String() string {
	return string(e)
}

func (e *OrganizationAPIKeyScope) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = OrganizationAPIKeyScope(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid OrganizationApiKeyScope", str)
	}
	return nil
}

func (e OrganizationAPIKeyScope) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *OrganizationAPIKeyScope) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e OrganizationAPIKeyScope) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type OrganizationRestrictionStatus string

const (
	OrganizationRestrictionStatusGated      OrganizationRestrictionStatus = "GATED"
	OrganizationRestrictionStatusFullAccess OrganizationRestrictionStatus = "FULL_ACCESS"
)

var AllOrganizationRestrictionStatus = []OrganizationRestrictionStatus{
	OrganizationRestrictionStatusGated,
	OrganizationRestrictionStatusFullAccess,
}

func (e OrganizationRestrictionStatus) IsValid() bool {
	switch e {
	case OrganizationRestrictionStatusGated, OrganizationRestrictionStatusFullAccess:
		return true
	}
	return false
}

func (e OrganizationRestrictionStatus) String() string {
	return string(e)
}

func (e *OrganizationRestrictionStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = OrganizationRestrictionStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid OrganizationRestrictionStatus", str)
	}
	return nil
}

func (e OrganizationRestrictionStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *OrganizationRestrictionStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e OrganizationRestrictionStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type OwnershipVerificationStatus string

const (
	OwnershipVerificationStatusVerificationPending     OwnershipVerificationStatus = "VERIFICATION_PENDING"
	OwnershipVerificationStatusVerificationSuccessfull OwnershipVerificationStatus = "VERIFICATION_SUCCESSFULL"
	OwnershipVerificationStatusVerificationExpired     OwnershipVerificationStatus = "VERIFICATION_EXPIRED"
	OwnershipVerificationStatusVerificationFailed      OwnershipVerificationStatus = "VERIFICATION_FAILED"
)

var AllOwnershipVerificationStatus = []OwnershipVerificationStatus{
	OwnershipVerificationStatusVerificationPending,
	OwnershipVerificationStatusVerificationSuccessfull,
	OwnershipVerificationStatusVerificationExpired,
	OwnershipVerificationStatusVerificationFailed,
}

func (e OwnershipVerificationStatus) IsValid() bool {
	switch e {
	case OwnershipVerificationStatusVerificationPending, OwnershipVerificationStatusVerificationSuccessfull, OwnershipVerificationStatusVerificationExpired, OwnershipVerificationStatusVerificationFailed:
		return true
	}
	return false
}

func (e OwnershipVerificationStatus) String() string {
	return string(e)
}

func (e *OwnershipVerificationStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = OwnershipVerificationStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid OwnershipVerificationStatus", str)
	}
	return nil
}

func (e OwnershipVerificationStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *OwnershipVerificationStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e OwnershipVerificationStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type RegistryType string

const (
	RegistryTypeOnChain  RegistryType = "ON_CHAIN"
	RegistryTypeOffChain RegistryType = "OFF_CHAIN"
)

var AllRegistryType = []RegistryType{
	RegistryTypeOnChain,
	RegistryTypeOffChain,
}

func (e RegistryType) IsValid() bool {
	switch e {
	case RegistryTypeOnChain, RegistryTypeOffChain:
		return true
	}
	return false
}

func (e RegistryType) String() string {
	return string(e)
}

func (e *RegistryType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = RegistryType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid RegistryType", str)
	}
	return nil
}

func (e RegistryType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *RegistryType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e RegistryType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ResourceConsumptionGroupDimension string

const (
	ResourceConsumptionGroupDimensionResourceConsumptionGroupDimensionUnspecified ResourceConsumptionGroupDimension = "RESOURCE_CONSUMPTION_GROUP_DIMENSION_UNSPECIFIED"
	ResourceConsumptionGroupDimensionResourceConsumptionGroupDimensionWorkflowID  ResourceConsumptionGroupDimension = "RESOURCE_CONSUMPTION_GROUP_DIMENSION_WORKFLOW_ID"
	ResourceConsumptionGroupDimensionResourceConsumptionGroupDimensionNetwork     ResourceConsumptionGroupDimension = "RESOURCE_CONSUMPTION_GROUP_DIMENSION_NETWORK"
	ResourceConsumptionGroupDimensionResourceConsumptionGroupDimensionDay         ResourceConsumptionGroupDimension = "RESOURCE_CONSUMPTION_GROUP_DIMENSION_DAY"
)

var AllResourceConsumptionGroupDimension = []ResourceConsumptionGroupDimension{
	ResourceConsumptionGroupDimensionResourceConsumptionGroupDimensionUnspecified,
	ResourceConsumptionGroupDimensionResourceConsumptionGroupDimensionWorkflowID,
	ResourceConsumptionGroupDimensionResourceConsumptionGroupDimensionNetwork,
	ResourceConsumptionGroupDimensionResourceConsumptionGroupDimensionDay,
}

func (e ResourceConsumptionGroupDimension) IsValid() bool {
	switch e {
	case ResourceConsumptionGroupDimensionResourceConsumptionGroupDimensionUnspecified, ResourceConsumptionGroupDimensionResourceConsumptionGroupDimensionWorkflowID, ResourceConsumptionGroupDimensionResourceConsumptionGroupDimensionNetwork, ResourceConsumptionGroupDimensionResourceConsumptionGroupDimensionDay:
		return true
	}
	return false
}

func (e ResourceConsumptionGroupDimension) String() string {
	return string(e)
}

func (e *ResourceConsumptionGroupDimension) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ResourceConsumptionGroupDimension(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ResourceConsumptionGroupDimension", str)
	}
	return nil
}

func (e ResourceConsumptionGroupDimension) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ResourceConsumptionGroupDimension) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ResourceConsumptionGroupDimension) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type SecretsAuthFlow string

const (
	SecretsAuthFlowBrowser         SecretsAuthFlow = "BROWSER"
	SecretsAuthFlowOwnerKeySigning SecretsAuthFlow = "OWNER_KEY_SIGNING"
)

var AllSecretsAuthFlow = []SecretsAuthFlow{
	SecretsAuthFlowBrowser,
	SecretsAuthFlowOwnerKeySigning,
}

func (e SecretsAuthFlow) IsValid() bool {
	switch e {
	case SecretsAuthFlowBrowser, SecretsAuthFlowOwnerKeySigning:
		return true
	}
	return false
}

func (e SecretsAuthFlow) String() string {
	return string(e)
}

func (e *SecretsAuthFlow) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SecretsAuthFlow(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SecretsAuthFlow", str)
	}
	return nil
}

func (e SecretsAuthFlow) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SecretsAuthFlow) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SecretsAuthFlow) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type SortingOrder string

const (
	SortingOrderAsc  SortingOrder = "ASC"
	SortingOrderDesc SortingOrder = "DESC"
)

var AllSortingOrder = []SortingOrder{
	SortingOrderAsc,
	SortingOrderDesc,
}

func (e SortingOrder) IsValid() bool {
	switch e {
	case SortingOrderAsc, SortingOrderDesc:
		return true
	}
	return false
}

func (e SortingOrder) String() string {
	return string(e)
}

func (e *SortingOrder) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SortingOrder(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SortingOrder", str)
	}
	return nil
}

func (e SortingOrder) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SortingOrder) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SortingOrder) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type SupportTicketProduct string

const (
	SupportTicketProductAce     SupportTicketProduct = "ACE"
	SupportTicketProductCre     SupportTicketProduct = "CRE"
	SupportTicketProductStreams SupportTicketProduct = "STREAMS"
	SupportTicketProductCrec    SupportTicketProduct = "CREC"
)

var AllSupportTicketProduct = []SupportTicketProduct{
	SupportTicketProductAce,
	SupportTicketProductCre,
	SupportTicketProductStreams,
	SupportTicketProductCrec,
}

func (e SupportTicketProduct) IsValid() bool {
	switch e {
	case SupportTicketProductAce, SupportTicketProductCre, SupportTicketProductStreams, SupportTicketProductCrec:
		return true
	}
	return false
}

func (e SupportTicketProduct) String() string {
	return string(e)
}

func (e *SupportTicketProduct) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SupportTicketProduct(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SupportTicketProduct", str)
	}
	return nil
}

func (e SupportTicketProduct) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SupportTicketProduct) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SupportTicketProduct) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type SupportTicketRequestType string

const (
	SupportTicketRequestTypeCreGeneralFeedback             SupportTicketRequestType = "cre_general_feedback"
	SupportTicketRequestTypeCreFeatureRequest              SupportTicketRequestType = "cre_feature_request"
	SupportTicketRequestTypeCreBugReport                   SupportTicketRequestType = "cre_bug_report"
	SupportTicketRequestTypeCreSupportRequest              SupportTicketRequestType = "cre_support_request"
	SupportTicketRequestTypeCreCustomerDeployAccessRequest SupportTicketRequestType = "cre_customer_deploy_access_request"
	SupportTicketRequestTypeCreOther                       SupportTicketRequestType = "cre_other"
)

var AllSupportTicketRequestType = []SupportTicketRequestType{
	SupportTicketRequestTypeCreGeneralFeedback,
	SupportTicketRequestTypeCreFeatureRequest,
	SupportTicketRequestTypeCreBugReport,
	SupportTicketRequestTypeCreSupportRequest,
	SupportTicketRequestTypeCreCustomerDeployAccessRequest,
	SupportTicketRequestTypeCreOther,
}

func (e SupportTicketRequestType) IsValid() bool {
	switch e {
	case SupportTicketRequestTypeCreGeneralFeedback, SupportTicketRequestTypeCreFeatureRequest, SupportTicketRequestTypeCreBugReport, SupportTicketRequestTypeCreSupportRequest, SupportTicketRequestTypeCreCustomerDeployAccessRequest, SupportTicketRequestTypeCreOther:
		return true
	}
	return false
}

func (e SupportTicketRequestType) String() string {
	return string(e)
}

func (e *SupportTicketRequestType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SupportTicketRequestType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SupportTicketRequestType", str)
	}
	return nil
}

func (e SupportTicketRequestType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SupportTicketRequestType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SupportTicketRequestType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type VaultPermission string

const (
	VaultPermissionVaultPermissionCreateSecrets VaultPermission = "VAULT_PERMISSION_CREATE_SECRETS"
	VaultPermissionVaultPermissionDeleteSecrets VaultPermission = "VAULT_PERMISSION_DELETE_SECRETS"
	VaultPermissionVaultPermissionUpdateSecrets VaultPermission = "VAULT_PERMISSION_UPDATE_SECRETS"
	VaultPermissionVaultPermissionListSecrets   VaultPermission = "VAULT_PERMISSION_LIST_SECRETS"
)

var AllVaultPermission = []VaultPermission{
	VaultPermissionVaultPermissionCreateSecrets,
	VaultPermissionVaultPermissionDeleteSecrets,
	VaultPermissionVaultPermissionUpdateSecrets,
	VaultPermissionVaultPermissionListSecrets,
}

func (e VaultPermission) IsValid() bool {
	switch e {
	case VaultPermissionVaultPermissionCreateSecrets, VaultPermissionVaultPermissionDeleteSecrets, VaultPermissionVaultPermissionUpdateSecrets, VaultPermissionVaultPermissionListSecrets:
		return true
	}
	return false
}

func (e VaultPermission) String() string {
	return string(e)
}

func (e *VaultPermission) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = VaultPermission(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid VaultPermission", str)
	}
	return nil
}

func (e VaultPermission) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *VaultPermission) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e VaultPermission) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type WorkflowDeploymentOrderByField string

const (
	WorkflowDeploymentOrderByFieldWorkflowID WorkflowDeploymentOrderByField = "WORKFLOW_ID"
	WorkflowDeploymentOrderByFieldDeployedAt WorkflowDeploymentOrderByField = "DEPLOYED_AT"
)

var AllWorkflowDeploymentOrderByField = []WorkflowDeploymentOrderByField{
	WorkflowDeploymentOrderByFieldWorkflowID,
	WorkflowDeploymentOrderByFieldDeployedAt,
}

func (e WorkflowDeploymentOrderByField) IsValid() bool {
	switch e {
	case WorkflowDeploymentOrderByFieldWorkflowID, WorkflowDeploymentOrderByFieldDeployedAt:
		return true
	}
	return false
}

func (e WorkflowDeploymentOrderByField) String() string {
	return string(e)
}

func (e *WorkflowDeploymentOrderByField) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = WorkflowDeploymentOrderByField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid WorkflowDeploymentOrderByField", str)
	}
	return nil
}

func (e WorkflowDeploymentOrderByField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *WorkflowDeploymentOrderByField) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e WorkflowDeploymentOrderByField) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type WorkflowDeploymentStatus string

const (
	WorkflowDeploymentStatusPending WorkflowDeploymentStatus = "PENDING"
	WorkflowDeploymentStatusFailed  WorkflowDeploymentStatus = "FAILED"
	WorkflowDeploymentStatusActive  WorkflowDeploymentStatus = "ACTIVE"
	WorkflowDeploymentStatusPaused  WorkflowDeploymentStatus = "PAUSED"
	WorkflowDeploymentStatusDeleted WorkflowDeploymentStatus = "DELETED"
)

var AllWorkflowDeploymentStatus = []WorkflowDeploymentStatus{
	WorkflowDeploymentStatusPending,
	WorkflowDeploymentStatusFailed,
	WorkflowDeploymentStatusActive,
	WorkflowDeploymentStatusPaused,
	WorkflowDeploymentStatusDeleted,
}

func (e WorkflowDeploymentStatus) IsValid() bool {
	switch e {
	case WorkflowDeploymentStatusPending, WorkflowDeploymentStatusFailed, WorkflowDeploymentStatusActive, WorkflowDeploymentStatusPaused, WorkflowDeploymentStatusDeleted:
		return true
	}
	return false
}

func (e WorkflowDeploymentStatus) String() string {
	return string(e)
}

func (e *WorkflowDeploymentStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = WorkflowDeploymentStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid WorkflowDeploymentStatus", str)
	}
	return nil
}

func (e WorkflowDeploymentStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *WorkflowDeploymentStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e WorkflowDeploymentStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type WorkflowExecutionClassifiedStatus string

const (
	WorkflowExecutionClassifiedStatusUnspecified WorkflowExecutionClassifiedStatus = "UNSPECIFIED"
	WorkflowExecutionClassifiedStatusSuccess     WorkflowExecutionClassifiedStatus = "SUCCESS"
	WorkflowExecutionClassifiedStatusUserError   WorkflowExecutionClassifiedStatus = "USER_ERROR"
	WorkflowExecutionClassifiedStatusSystemError WorkflowExecutionClassifiedStatus = "SYSTEM_ERROR"
)

var AllWorkflowExecutionClassifiedStatus = []WorkflowExecutionClassifiedStatus{
	WorkflowExecutionClassifiedStatusUnspecified,
	WorkflowExecutionClassifiedStatusSuccess,
	WorkflowExecutionClassifiedStatusUserError,
	WorkflowExecutionClassifiedStatusSystemError,
}

func (e WorkflowExecutionClassifiedStatus) IsValid() bool {
	switch e {
	case WorkflowExecutionClassifiedStatusUnspecified, WorkflowExecutionClassifiedStatusSuccess, WorkflowExecutionClassifiedStatusUserError, WorkflowExecutionClassifiedStatusSystemError:
		return true
	}
	return false
}

func (e WorkflowExecutionClassifiedStatus) String() string {
	return string(e)
}

func (e *WorkflowExecutionClassifiedStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = WorkflowExecutionClassifiedStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid WorkflowExecutionClassifiedStatus", str)
	}
	return nil
}

func (e WorkflowExecutionClassifiedStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *WorkflowExecutionClassifiedStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e WorkflowExecutionClassifiedStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type WorkflowExecutionOrderByField string

const (
	WorkflowExecutionOrderByFieldID         WorkflowExecutionOrderByField = "ID"
	WorkflowExecutionOrderByFieldStatus     WorkflowExecutionOrderByField = "STATUS"
	WorkflowExecutionOrderByFieldStartedAt  WorkflowExecutionOrderByField = "STARTED_AT"
	WorkflowExecutionOrderByFieldCreditUsed WorkflowExecutionOrderByField = "CREDIT_USED"
)

var AllWorkflowExecutionOrderByField = []WorkflowExecutionOrderByField{
	WorkflowExecutionOrderByFieldID,
	WorkflowExecutionOrderByFieldStatus,
	WorkflowExecutionOrderByFieldStartedAt,
	WorkflowExecutionOrderByFieldCreditUsed,
}

func (e WorkflowExecutionOrderByField) IsValid() bool {
	switch e {
	case WorkflowExecutionOrderByFieldID, WorkflowExecutionOrderByFieldStatus, WorkflowExecutionOrderByFieldStartedAt, WorkflowExecutionOrderByFieldCreditUsed:
		return true
	}
	return false
}

func (e WorkflowExecutionOrderByField) String() string {
	return string(e)
}

func (e *WorkflowExecutionOrderByField) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = WorkflowExecutionOrderByField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid WorkflowExecutionOrderByField", str)
	}
	return nil
}

func (e WorkflowExecutionOrderByField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *WorkflowExecutionOrderByField) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e WorkflowExecutionOrderByField) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type WorkflowExecutionStatus string

const (
	WorkflowExecutionStatusUnknown     WorkflowExecutionStatus = "UNKNOWN"
	WorkflowExecutionStatusUnspecified WorkflowExecutionStatus = "UNSPECIFIED"
	WorkflowExecutionStatusTriggered   WorkflowExecutionStatus = "TRIGGERED"
	WorkflowExecutionStatusInProgress  WorkflowExecutionStatus = "IN_PROGRESS"
	WorkflowExecutionStatusSuccess     WorkflowExecutionStatus = "SUCCESS"
	WorkflowExecutionStatusFailure     WorkflowExecutionStatus = "FAILURE"
)

var AllWorkflowExecutionStatus = []WorkflowExecutionStatus{
	WorkflowExecutionStatusUnknown,
	WorkflowExecutionStatusUnspecified,
	WorkflowExecutionStatusTriggered,
	WorkflowExecutionStatusInProgress,
	WorkflowExecutionStatusSuccess,
	WorkflowExecutionStatusFailure,
}

func (e WorkflowExecutionStatus) IsValid() bool {
	switch e {
	case WorkflowExecutionStatusUnknown, WorkflowExecutionStatusUnspecified, WorkflowExecutionStatusTriggered, WorkflowExecutionStatusInProgress, WorkflowExecutionStatusSuccess, WorkflowExecutionStatusFailure:
		return true
	}
	return false
}

func (e WorkflowExecutionStatus) String() string {
	return string(e)
}

func (e *WorkflowExecutionStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = WorkflowExecutionStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid WorkflowExecutionStatus", str)
	}
	return nil
}

func (e WorkflowExecutionStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *WorkflowExecutionStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e WorkflowExecutionStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type WorkflowOrderByField string

const (
	WorkflowOrderByFieldName       WorkflowOrderByField = "NAME"
	WorkflowOrderByFieldStatus     WorkflowOrderByField = "STATUS"
	WorkflowOrderByFieldExecutedAt WorkflowOrderByField = "EXECUTED_AT"
)

var AllWorkflowOrderByField = []WorkflowOrderByField{
	WorkflowOrderByFieldName,
	WorkflowOrderByFieldStatus,
	WorkflowOrderByFieldExecutedAt,
}

func (e WorkflowOrderByField) IsValid() bool {
	switch e {
	case WorkflowOrderByFieldName, WorkflowOrderByFieldStatus, WorkflowOrderByFieldExecutedAt:
		return true
	}
	return false
}

func (e WorkflowOrderByField) String() string {
	return string(e)
}

func (e *WorkflowOrderByField) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = WorkflowOrderByField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid WorkflowOrderByField", str)
	}
	return nil
}

func (e WorkflowOrderByField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *WorkflowOrderByField) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e WorkflowOrderByField) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
