// Code generated by github.com/gqlgo/gqlgenc, DO NOT EDIT.

package client

import (
	"context"
	"time"

	"github.com/gqlgo/gqlgenc/clientv2"
)

type Client struct {
	Client *clientv2.Client
}

func NewClient(cli clientv2.HttpClient, baseURL string, options *clientv2.Options, interceptors ...clientv2.RequestInterceptor) *Client {
	return &Client{Client: clientv2.NewClient(cli, baseURL, options, interceptors...)}
}

type GetAccountDetails_GetAccountDetails struct {
	CreatedAt      time.Time    "json:\"createdAt\" graphql:\"createdAt\""
	DisplayName    string       "json:\"displayName\" graphql:\"displayName\""
	EmailAddress   string       "json:\"emailAddress\" graphql:\"emailAddress\""
	InvitedAt      *time.Time   "json:\"invitedAt,omitempty\" graphql:\"invitedAt\""
	InvitedByUser  *string      "json:\"invitedByUser,omitempty\" graphql:\"invitedByUser\""
	JoinedAt       *time.Time   "json:\"joinedAt,omitempty\" graphql:\"joinedAt\""
	MemberID       string       "json:\"memberId\" graphql:\"memberId\""
	MemberStatus   MemberStatus "json:\"memberStatus\" graphql:\"memberStatus\""
	MemberType     *MemberType  "json:\"memberType,omitempty\" graphql:\"memberType\""
	OrganizationID string       "json:\"organizationId\" graphql:\"organizationId\""
	RemovedAt      *time.Time   "json:\"removedAt,omitempty\" graphql:\"removedAt\""
	RemovedByUser  *string      "json:\"removedByUser,omitempty\" graphql:\"removedByUser\""
	UpdatedAt      time.Time    "json:\"updatedAt\" graphql:\"updatedAt\""
	UserID         *string      "json:\"userId,omitempty\" graphql:\"userId\""
}

func (t *GetAccountDetails_GetAccountDetails) GetCreatedAt() *time.Time {
	if t == nil {
		t = &GetAccountDetails_GetAccountDetails{}
	}
	return &t.CreatedAt
}
func (t *GetAccountDetails_GetAccountDetails) GetDisplayName() string {
	if t == nil {
		t = &GetAccountDetails_GetAccountDetails{}
	}
	return t.DisplayName
}
func (t *GetAccountDetails_GetAccountDetails) GetEmailAddress() string {
	if t == nil {
		t = &GetAccountDetails_GetAccountDetails{}
	}
	return t.EmailAddress
}
func (t *GetAccountDetails_GetAccountDetails) GetInvitedAt() *time.Time {
	if t == nil {
		t = &GetAccountDetails_GetAccountDetails{}
	}
	return t.InvitedAt
}
func (t *GetAccountDetails_GetAccountDetails) GetInvitedByUser() *string {
	if t == nil {
		t = &GetAccountDetails_GetAccountDetails{}
	}
	return t.InvitedByUser
}
func (t *GetAccountDetails_GetAccountDetails) GetJoinedAt() *time.Time {
	if t == nil {
		t = &GetAccountDetails_GetAccountDetails{}
	}
	return t.JoinedAt
}
func (t *GetAccountDetails_GetAccountDetails) GetMemberID() string {
	if t == nil {
		t = &GetAccountDetails_GetAccountDetails{}
	}
	return t.MemberID
}
func (t *GetAccountDetails_GetAccountDetails) GetMemberStatus() *MemberStatus {
	if t == nil {
		t = &GetAccountDetails_GetAccountDetails{}
	}
	return &t.MemberStatus
}
func (t *GetAccountDetails_GetAccountDetails) GetMemberType() *MemberType {
	if t == nil {
		t = &GetAccountDetails_GetAccountDetails{}
	}
	return t.MemberType
}
func (t *GetAccountDetails_GetAccountDetails) GetOrganizationID() string {
	if t == nil {
		t = &GetAccountDetails_GetAccountDetails{}
	}
	return t.OrganizationID
}
func (t *GetAccountDetails_GetAccountDetails) GetRemovedAt() *time.Time {
	if t == nil {
		t = &GetAccountDetails_GetAccountDetails{}
	}
	return t.RemovedAt
}
func (t *GetAccountDetails_GetAccountDetails) GetRemovedByUser() *string {
	if t == nil {
		t = &GetAccountDetails_GetAccountDetails{}
	}
	return t.RemovedByUser
}
func (t *GetAccountDetails_GetAccountDetails) GetUpdatedAt() *time.Time {
	if t == nil {
		t = &GetAccountDetails_GetAccountDetails{}
	}
	return &t.UpdatedAt
}
func (t *GetAccountDetails_GetAccountDetails) GetUserID() *string {
	if t == nil {
		t = &GetAccountDetails_GetAccountDetails{}
	}
	return t.UserID
}

type GetOrganizationDetails_GetOrganization struct {
	ActiveStatus      EntityActiveStatus            "json:\"activeStatus\" graphql:\"activeStatus\""
	CreatedAt         time.Time                     "json:\"createdAt\" graphql:\"createdAt\""
	DisplayName       string                        "json:\"displayName\" graphql:\"displayName\""
	OrganizationID    string                        "json:\"organizationId\" graphql:\"organizationId\""
	RestrictionStatus OrganizationRestrictionStatus "json:\"restrictionStatus\" graphql:\"restrictionStatus\""
	UpdatedAt         time.Time                     "json:\"updatedAt\" graphql:\"updatedAt\""
}

func (t *GetOrganizationDetails_GetOrganization) GetActiveStatus() *EntityActiveStatus {
	if t == nil {
		t = &GetOrganizationDetails_GetOrganization{}
	}
	return &t.ActiveStatus
}
func (t *GetOrganizationDetails_GetOrganization) GetCreatedAt() *time.Time {
	if t == nil {
		t = &GetOrganizationDetails_GetOrganization{}
	}
	return &t.CreatedAt
}
func (t *GetOrganizationDetails_GetOrganization) GetDisplayName() string {
	if t == nil {
		t = &GetOrganizationDetails_GetOrganization{}
	}
	return t.DisplayName
}
func (t *GetOrganizationDetails_GetOrganization) GetOrganizationID() string {
	if t == nil {
		t = &GetOrganizationDetails_GetOrganization{}
	}
	return t.OrganizationID
}
func (t *GetOrganizationDetails_GetOrganization) GetRestrictionStatus() *OrganizationRestrictionStatus {
	if t == nil {
		t = &GetOrganizationDetails_GetOrganization{}
	}
	return &t.RestrictionStatus
}
func (t *GetOrganizationDetails_GetOrganization) GetUpdatedAt() *time.Time {
	if t == nil {
		t = &GetOrganizationDetails_GetOrganization{}
	}
	return &t.UpdatedAt
}

type GetAccountDetails struct {
	GetAccountDetails *GetAccountDetails_GetAccountDetails "json:\"getAccountDetails,omitempty\" graphql:\"getAccountDetails\""
}

func (t *GetAccountDetails) GetGetAccountDetails() *GetAccountDetails_GetAccountDetails {
	if t == nil {
		t = &GetAccountDetails{}
	}
	return t.GetAccountDetails
}

type GetOrganizationDetails struct {
	GetOrganization *GetOrganizationDetails_GetOrganization "json:\"getOrganization,omitempty\" graphql:\"getOrganization\""
}

func (t *GetOrganizationDetails) GetGetOrganization() *GetOrganizationDetails_GetOrganization {
	if t == nil {
		t = &GetOrganizationDetails{}
	}
	return t.GetOrganization
}

const GetAccountDetailsDocument = `query GetAccountDetails {
	getAccountDetails {
		memberId
		userId
		organizationId
		emailAddress
		displayName
		memberType
		memberStatus
		createdAt
		updatedAt
		invitedByUser
		invitedAt
		joinedAt
		removedByUser
		removedAt
	}
}
`

func (c *Client) GetAccountDetails(ctx context.Context, interceptors ...clientv2.RequestInterceptor) (*GetAccountDetails, error) {
	vars := map[string]any{}

	var res GetAccountDetails
	if err := c.Client.Post(ctx, "GetAccountDetails", GetAccountDetailsDocument, &res, vars, interceptors...); err != nil {
		if c.Client.ParseDataWhenErrors {
			return &res, err
		}

		return nil, err
	}

	return &res, nil
}

const GetOrganizationDetailsDocument = `query GetOrganizationDetails {
	getOrganization {
		organizationId
		displayName
		createdAt
		updatedAt
		restrictionStatus
		activeStatus
	}
}
`

func (c *Client) GetOrganizationDetails(ctx context.Context, interceptors ...clientv2.RequestInterceptor) (*GetOrganizationDetails, error) {
	vars := map[string]any{}

	var res GetOrganizationDetails
	if err := c.Client.Post(ctx, "GetOrganizationDetails", GetOrganizationDetailsDocument, &res, vars, interceptors...); err != nil {
		if c.Client.ParseDataWhenErrors {
			return &res, err
		}

		return nil, err
	}

	return &res, nil
}

var DocumentOperationNames = map[string]string{
	GetAccountDetailsDocument:      "GetAccountDetails",
	GetOrganizationDetailsDocument: "GetOrganizationDetails",
}
